### ISSUE TITLE
Initial code reach out

### ISSUE THREAD

**Issue by rdpeake** [MEGA65/mega65-code-snippets#1]
We are trying to collate all existing code snippets - or get people who have made useful code they want to share to make them into shareable snippets or repos that we can try to maintain a list of known snippets to make it easier to share these things around.

Things like changing screen colours and layouts (some of these may also be in the manual, but having them here may not be a bad thing), loaders, and examples for DMA, and other memory management tools etc.

Also any projects for mega you wish to share to bring attention also include those below as well

Please comment bellow with links to gist, or githubs containing code snippets that currently exist
![image](https://user-images.githubusercontent.com/3162788/117690866-75217780-b1fa-11eb-856a-8fbcbfc70ae5.png)

**Comment by rdpeake** [comment]
Projects from paul mentioned in discord: 
https://github.com/mega65/mega65-weeIP - TCP/IP stack for MEGA65
Wolfenstein-style 3D engine port -- https://github.com/gardners/raycaster

**Comment by L3114** [comment]
You want to add the repos from sy2002 https://github.com/sy2002

namely
https://github.com/sy2002/zxuno4mega65
https://github.com/sy2002/gbc4mega65
https://github.com/sy2002/QNICE-FPGA
https://github.com/sy2002/MiSTer2MEGA65

**Comment by L3114** [comment]
m65dbg an enhanced remote serial debugger/monitor for the mega65 project https://github.com/gurcei/m65dbg
megafighter an attempt to create an open-source fighter game for the MEGA65 https://github.com/gurcei/megafighter

**Comment by L3114** [comment]
Bit Shifter's Z Interpreter https://github.com/Edilbert/BSZ
BSA The Bit Shift Assembler for the 6502 / 65C02 / 45GS02 CPU https://github.com/Edilbert/BSA

**Comment by GeorgRottensteiner** [comment]
HitBlock65:
A small game, initially created for Shallan's compo: https://github.com/GeorgRottensteiner/HitBlock-Mega65

C64Studio:
A IDE, currently mostly tailored to C64 development, also has Mega65 assembly support (in ACME syntax), BASIC 10 "compiler" and various other assembler dialects:
https://github.com/GeorgRottensteiner/C64Studio

**Comment by L3114** [comment]
just-pixel a pixler for the MEGA65 by Marc Teufel inspired by Zoomatic (Panoramic Designs) https://github.com/mteufel/just-pixel

and

https://github.com/mteufel/m65-examples

**Comment by L3114** [comment]
Manche 0.14A Beta a front-end for the Peppito MOD player https://github.com/M3wP/Manche
M3wP Solitaire! https://github.com/M3wP/M3wPSolitaire
https://github.com/M3wP/MEGA65Tools

M3wP also has a bunch of GEOS stuff, not sure if to add this here too or if that would be another section
see https://github.com/M3wP?tab=repositories

**Comment by L3114** [comment]
https://github.com/smnjameson
Mega65Toolkit https://github.com/smnjameson/Mega65Toolkit
https://github.com/smnjameson/m65_example_code

**Comment by L3114** [comment]
https://github.com/steph72
dragonrock-mega65 a role playing game for the MEGA65. https://github.com/steph72/dragonrock-mega65
m65wator a population dynamics simulation for the MEGA65 https://github.com/steph72/m65wator
megarogue beginnings of a roguelike game engine for the mega65 https://github.com/steph72/megarogue
https://github.com/steph72/mega65puyo

**Comment by L3114** [comment]
mega65-basic BASIC interpreter for the Mega 65 Computer https://github.com/paulscottrobson/mega65-basic

**Comment by L3114** [comment]
MEGA65-SDK This SDK is just a repository including all compontents provided from external repositories.  https://github.com/SvOlli/mega65-sdk
C65 Firmware Build Kit this is a repository intended for developing the kernal of a C65/MEGA65 system. https://github.com/SvOlli/c65-firmware

**Comment by gardners** [comment]
Also worth documenting the various things in github.com/mega65/mega65-tools
(We should update the README.md there to be actually useful, too)

**Comment by gardners** [comment]
also: https://github.com/smnjameson/Mega65Toolkit

**Comment by smnjameson** [comment]
https://github.com/smnjameson/M65_Examples

**Comment by rdpeake** [comment]
All of these have been added to the list
